const catalogRows = `
CP10\tFRUITY SNACKS APPLES & OATMEAL\tPremios
CP09\tFRUITY SNACKS CRANBERRIES & OATMEAL\tPremios
CGJ1\tJERKY MINI STRIPS WITH REAL CHICKEN\tPremios
CKI1\tKITTEN INDOOR 7 LBS\tScience Diet
LM13\tLATA METABOLIC 13 ONZ\tPrescription Diet
CLZF\tLATA Z/D FELINO 5.5 ONZ\tPrescription Diet
CLA0\tPD A/D CANINE/FELINE LATA 5.5 ONZ\tPrescription Diet
CB16\tPD BIOME CANINO 16 LBS\tPrescription Diet
CBC8\tPD BIOME CANINO 8 LBS\tPrescription Diet
CBF4\tPD BIOME FELINO 4 LBS\tPrescription Diet
CBF8\tPD BIOME FELINO 8 LBS\tPrescription Diet
CC17\tPD C/D MULTICARE CANINE 17.6 LBS\tPrescription Diet
CC10\tPD C/D MULTICARE CANINE 8.5 LBS\tPrescription Diet
CFC2\tPD C/D MULTICARE FELINE 4 LBS\tPrescription Diet
CFC1\tPD C/D MULTICARE FELINE LATA 5.5 ONZ\tPrescription Diet
CFC4\tPD C/D MULTICARE STRESS FELINE 4 LBS\tPrescription Diet
CDD2\tPD DERM COMPLETE 14.3 LBS\tPrescription Diet
CDD1\tPD DERM COMPLETE 6 LBS\tPrescription Diet
CGH1\tPD HYPO TREATS CANINE\tPremios
CI17\tPD I/D CANINE 17.6 LBS\tPrescription Diet
CI08\tPD I/D CANINE 8.5 LBS\tPrescription Diet
CLI1\tPD I/D CANINE CHICKEN & VEGETABLES 12.5 OZ\tPrescription Diet
CLI5\tPD I/D CANINE CHICKEN & VEGETABLES 5.5 OZ\tPrescription Diet
CLI0\tPD I/D CANINE LATA 13 ONZ\tPrescription Diet
CIF4\tPD I/D FELINE 4 LBS\tPrescription Diet
CIDF\tPD I/D FELINE LATA 5.5 ONZ\tPrescription Diet
CIS7\tPD I/D SMALL BITES CANINE 7 LBS\tPrescription Diet
CJ27\tPD J/D CANINE 27.5 LBS\tPrescription Diet
CJ08\tPD J/D CANINE 8.5 LBS\tPrescription Diet
CK15\tPD K/D CANINE 1.5 KG\tPrescription Diet
CK17\tPD K/D CANINE 17.6 LBS\tPrescription Diet
CK08\tPD K/D CANINE 8.5 LBS\tPrescription Diet
CLK0\tPD K/D CANINE LATA 13 ONZ\tPrescription Diet
CFK1\tPD K/D FELINE 4 LBS\tPrescription Diet
CFK2\tPD K/D FELINE LATA 5.5 ONZ\tPrescription Diet
CLL1\tPD L/D CANINE LATA 13 ONZ\tPrescription Diet
CLD1\tPD L/D CANINO 17.6 LBS\tPrescription Diet
CMC2\tPD METABOLIC CANINE 27.5 LBS\tPrescription Diet
CM03\tPD METABOLIC CANINE 7.7 LBS\tPrescription Diet
CGM1\tPD METABOLIC CANINE TREATS\tPremios
CM02\tPD METABOLIC CANINO 17.6 LBS\tPrescription Diet
CMF1\tPD METABOLIC FELINE 4 LBS\tPrescription Diet
CMF2\tPD METABOLIC FELINE 8.5 LBS\tPrescription Diet
CMM8\tPD METABOLIC + MOBILITY J/D CANINE 8.5 LBS\tPrescription Diet
COC1\tPD ONC CANINO 15 LBS\tPrescription Diet
COC6\tPD ONC CANINO 6 LBS\tPrescription Diet
COCL\tPD ONC CANINO LATA 12.5 ONZ\tPrescription Diet
COF7\tPD ONC FELINO 7 LBS\tPrescription Diet
COFL\tPD ONC FELINO LATA 2.9 ONZ\tPrescription Diet
CR17\tPD R/D CANINE 17.6 LBS\tPrescription Diet
CR08\tPD R/D CANINE 8.5 LBS\tPrescription Diet
CRF4\tPD R/D FELINO 4 LBS\tPrescription Diet
CU08\tPD U/D CANINE 8.5 LBS\tPrescription Diet
CW17\tPD W/D MULTI-BENEFIT CANINE 17.6 LBS\tPrescription Diet
CW27\tPD W/D MULTI-BENEFIT CANINE 27.5 LBS\tPrescription Diet
CW08\tPD W/D MULTI-BENEFIT CANINE 8.5 LBS\tPrescription Diet
CLW0\tPD W/D MULTI-BENEFIT CANINE LATA 13 ONZ\tPrescription Diet
CWF4\tPD W/D MULTI-BENEFIT FELINE 4 LBS\tPrescription Diet
CZ17\tPD Z/D CANINE 17.6 LBS\tPrescription Diet
CZU8\tPD Z/D CANINE 8 LBS\tPrescription Diet
CLZ0\tPD Z/D CANINE LATA 13 ONZ\tPrescription Diet
CLP1\tSD PUPPY LATA 13 ONZ\tScience Diet
CS75\tSD ADULT 7+ 7.5 KG\tScience Diet
CS12\tSD ADULT 7+ 12 KG\tScience Diet
CFA7\tSD ADULT 7+ FELINE 4 LBS\tScience Diet
CLA4\tSD ADULT 7+ LATA 13 ONZ\tScience Diet
CSS2\tSD ADULT 7+ SMALL BITES 15 LBS\tScience Diet
CSS4\tSD ADULT 7+ SMALL BITES 2 KG\tScience Diet
CST3\tSD ADULT 7+ SMALL PAWS 4.5 LBS\tScience Diet
CA75\tSD ADULT 7.5 KG\tScience Diet
CF16\tSD ADULT FELINE 16 LBS\tScience Diet
CFM4\tSD ADULT FELINE 4 LBS\tScience Diet
CFM7\tSD ADULT FELINE 7 LBS\tScience Diet
CFL4\tSD ADULT FELINE LIGHT 4 LBS\tScience Diet
CFL8\tSD ADULT FELINE LIGHT 7 LBS\tScience Diet
CFSS\tSD ADULT FELINO SENSITIVE 3.5 LBS\tScience Diet
CFH1\tSD ADULT HAIRBALL CONTROL 3.5 LBS\tScience Diet
CC15\tSD ADULT LAMB & RICE 15.5 LBS\tScience Diet
CCM0\tSD ADULT LAMB & RICE 33 LBS\tScience Diet
CST9\tSD ADULT LAMB SMALL PAWS 4.5 LBS\tScience Diet
CLB1\tSD ADULT LARGE BREED 15 KG\tScience Diet
CEA1\tSD ADULT LATA 13 ONZ\tScience Diet
CL15\tSD ADULT LIGHT 15 LBS\tScience Diet
CL30\tSD ADULT LIGHT 30 LBS\tScience Diet
CST7\tSD ADULT LIGHT SMALL PAWS 15.5 LBS\tScience Diet
CLST\tSD ADULT LIGHT SMALL PAWS 4.5 LBS\tScience Diet
CLSB\tSD ADULT SB LAMB & RICE 15.5 LBS\tScience Diet
CCM4\tSD ADULT SB LAMB & RICE 4.5 LBS\tScience Diet
CSS7\tSD ADULT SENSITIVE STOMACH & SKIN 15.5 LBS\tScience Diet
CSS1\tSD ADULT SENSITIVE STOMACH & SKIN 4 LB\tScience Diet
CMS3\tSD ADULT SMALL BITES 15 LBS\tScience Diet
CMS4\tSD ADULT SMALL BITES 2 KG\tScience Diet
CST5\tSD ADULT SMALL PAWS 15.5 LBS\tScience Diet
CST2\tSD ADULT SMALL PAWS 4.5 LBS\tScience Diet
CM17\tSD ADULTO 15 KG\tScience Diet
CM3K\tSD ADULTO 3 KG\tScience Diet
CPF4\tSD FELINO ADULT 7+ TD CHICKEN POUCHE\tScience Diet
CPF1\tSD FELINO ADULTO TD CHICKEN POUCHE\tScience Diet
CPF3\tSD FELINO ADULTO TD OCEAN FISH POUCHE\tScience Diet
CPF2\tSD FELINO ADULTO TD TUNA POUCHE\tScience Diet
CFP4\tSD KITTEN 3.5 LBS\tScience Diet
CFP7\tSD KITTEN 7 LBS\tScience Diet
CLK1\tSD KITTEN LATA 5.5 ONZ\tScience Diet
CPF5\tSD KITTEN TD CHICKEN POUCHE\tScience Diet
CPD2\tSD PERFECT DIGESTION CAN 12 LB\tScience Diet
CPD1\tSD PERFECT DIGESTION CAN 3.5 LB\tScience Diet
CPD3\tSD PERFECT DIGESTION FELINO 3.5 LB\tScience Diet
CG15\tSD PUPPY 15.5 LBS\tScience Diet
CP05\tSD PUPPY 4.5 LBS\tScience Diet
CPL1\tSD PUPPY LARGE BREED 15.5 LBS\tScience Diet
CPL3\tSD PUPPY LARGE BREED 27.5 LBS\tScience Diet
CP27\tSD PUPPY ORG 27.5 LBS\tScience Diet
CPS2\tSD PUPPY SMALL BITES 12.5 LBS\tScience Diet
CPS5\tSD PUPPY SMALL BITES 4.5 LBS\tScience Diet
CST8\tSD PUPPY SMALL PAWS 12.5 LBS\tScience Diet
CST1\tSD PUPPY SMALL PAWS 4.5 LBS\tScience Diet
CP01\tSOFT SAVORIES BEEF & CHEDDAR\tPremios
CP03\tSOFT SAVORIES PEANUT BUTTER & BANANA\tPremios
CGA1\tTRAINING TREATS SOFT AND CHEWY\tPremios
`.trim();

export const DEFAULT_PRODUCTS = catalogRows.split("\n").map((row) => {
  const [code, description, category] = row.split("\t");
  return { code, description, presentation: "", category };
});
